{
  "formatVersion": "1.1",
  "component": {
    "group": "com.anchor",
    "module": "Anchor",
    "version": "1.0.0-24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Anchor-1.0.0-24.jar",
          "url": "Anchor-1.0.0-24.jar",
          "size": 14569,
          "sha512": "a884208814f95a3255ecc2839f86b83edb28320dc224c1f07d2316638af6ecf730b49ceda0f5434a7c80c1609322039960e2fe42bb10c4b7e3621e5eb140ac26",
          "sha256": "556ff8584e8b230314d55e656059691e3b0ad8d7d3aab4e6a8199e9ce3e21b84",
          "sha1": "d2f7c76bd96d2eb4965d314732bfbdf736e15500",
          "md5": "9429129268cd4e2393b8d07b8448368b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.composed",
          "module": "composed",
          "version": {
            "requires": "1.0.1-245"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          }
        }
      ],
      "files": [
        {
          "name": "Anchor-1.0.0-24.jar",
          "url": "Anchor-1.0.0-24.jar",
          "size": 14569,
          "sha512": "a884208814f95a3255ecc2839f86b83edb28320dc224c1f07d2316638af6ecf730b49ceda0f5434a7c80c1609322039960e2fe42bb10c4b7e3621e5eb140ac26",
          "sha256": "556ff8584e8b230314d55e656059691e3b0ad8d7d3aab4e6a8199e9ce3e21b84",
          "sha1": "d2f7c76bd96d2eb4965d314732bfbdf736e15500",
          "md5": "9429129268cd4e2393b8d07b8448368b"
        }
      ]
    }
  ]
}
