{
  "formatVersion": "1.1",
  "component": {
    "group": "com.anchor",
    "module": "Anchor",
    "version": "1.0.0-24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Anchor-1.0.0-24.jar",
          "url": "Anchor-1.0.0-24.jar",
          "size": 13120,
          "sha512": "3f1fc2006f96225c6c493f0133652cd39b897778521b073a258c51fe542b5506952075721409c02f13652745786eee32de4e146194ecea30602babbd4945a7d3",
          "sha256": "79fb21586c6bfe8b4616d854c1743ea2c84e8c4d8701bcdaaf26721ce88e9c47",
          "sha1": "4ca79bee915bcd26afe2d30d55810e89576daef0",
          "md5": "4f173770734514ade82f4efcccc90ded"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.composed",
          "module": "composed",
          "version": {
            "requires": "1.0.1-245"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          }
        }
      ],
      "files": [
        {
          "name": "Anchor-1.0.0-24.jar",
          "url": "Anchor-1.0.0-24.jar",
          "size": 13120,
          "sha512": "3f1fc2006f96225c6c493f0133652cd39b897778521b073a258c51fe542b5506952075721409c02f13652745786eee32de4e146194ecea30602babbd4945a7d3",
          "sha256": "79fb21586c6bfe8b4616d854c1743ea2c84e8c4d8701bcdaaf26721ce88e9c47",
          "sha1": "4ca79bee915bcd26afe2d30d55810e89576daef0",
          "md5": "4f173770734514ade82f4efcccc90ded"
        }
      ]
    }
  ]
}
