{
  "formatVersion": "1.1",
  "component": {
    "group": "com.anchor",
    "module": "Anchor",
    "version": "1.0.0-21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Anchor-1.0.0-21.jar",
          "url": "Anchor-1.0.0-21.jar",
          "size": 14565,
          "sha512": "8888383ba66df76d835d6e1cd8e329de0031281b0ad1cd7065738a743f8e29e5262908226b8a523210a2e1ff1ddc5c7d3457041de7f86dd423e2a1b70681d773",
          "sha256": "ff6260290d73e473a32be51d932f730e826eb0f1da096430fa36158f6d966240",
          "sha1": "672be0139ba705f7b3a8d9623a7ed304a49e2fbb",
          "md5": "e779c3160c980352ee85e323ac2fe827"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.composed",
          "module": "composed",
          "version": {
            "requires": "1.0.1-215"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          }
        }
      ],
      "files": [
        {
          "name": "Anchor-1.0.0-21.jar",
          "url": "Anchor-1.0.0-21.jar",
          "size": 14565,
          "sha512": "8888383ba66df76d835d6e1cd8e329de0031281b0ad1cd7065738a743f8e29e5262908226b8a523210a2e1ff1ddc5c7d3457041de7f86dd423e2a1b70681d773",
          "sha256": "ff6260290d73e473a32be51d932f730e826eb0f1da096430fa36158f6d966240",
          "sha1": "672be0139ba705f7b3a8d9623a7ed304a49e2fbb",
          "md5": "e779c3160c980352ee85e323ac2fe827"
        }
      ]
    }
  ]
}
