{
  "formatVersion": "1.1",
  "component": {
    "group": "com.anchor",
    "module": "Anchor",
    "version": "1.0.0-21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Anchor-1.0.0-21.jar",
          "url": "Anchor-1.0.0-21.jar",
          "size": 13117,
          "sha512": "465f490acd2d6bc4fcfd1f928bb575c94c0447c3aa47e8e4b039a9d9cdc973731966087ca448a393888001ca39b881c610ba558dc8d3d85732942567b7c3a606",
          "sha256": "6ac2f3a4aef45490ec85766ac32e4b5a13a53f36d10993ff5186ba0b81d14984",
          "sha1": "e12e038766717d8aee8627ef4b670300f41e5e57",
          "md5": "f2c62a90d22d8de6b26d94f223bc6fce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.composed",
          "module": "composed",
          "version": {
            "requires": "1.0.1-215"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          }
        }
      ],
      "files": [
        {
          "name": "Anchor-1.0.0-21.jar",
          "url": "Anchor-1.0.0-21.jar",
          "size": 13117,
          "sha512": "465f490acd2d6bc4fcfd1f928bb575c94c0447c3aa47e8e4b039a9d9cdc973731966087ca448a393888001ca39b881c610ba558dc8d3d85732942567b7c3a606",
          "sha256": "6ac2f3a4aef45490ec85766ac32e4b5a13a53f36d10993ff5186ba0b81d14984",
          "sha1": "e12e038766717d8aee8627ef4b670300f41e5e57",
          "md5": "f2c62a90d22d8de6b26d94f223bc6fce"
        }
      ]
    }
  ]
}
